# Generated by Django 3.0.5 on 2022-05-07 20:59

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20220507_2059'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['create_on'],
            },
        ),
        migrations.CreateModel(
            name='CurricularComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('total_workload', models.IntegerField(verbose_name='Carga horária total')),
                ('weekly_workload', models.IntegerField(verbose_name='Carga horária semanal')),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None)),
                ('core', models.CharField(blank=True, choices=[('Basico', 'Basico'), ('Tecnologico', 'Tecnologico'), ('Integrador', 'Integrador'), ('Complementar', 'Complementar')], help_text='*', max_length=12, verbose_name='Núcleo')),
                ('type', models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Progressao Parcial', 'Progressao Parcial')], default='Regular', help_text='*', max_length=18, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'CurricularComponent',
                'verbose_name_plural': 'CurricularComponents',
                'ordering': ['create_on'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('start_date', models.DateField(verbose_name='Data de Inicio')),
                ('end_date', models.DateField(verbose_name='Data de Fim')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('start', models.TimeField(verbose_name='Hora de Início da Aula')),
                ('class_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='school.ClassShift', verbose_name='ClassShift')),
            ],
            options={
                'verbose_name': 'TimeTable',
                'verbose_name_plural': 'TimeTables',
                'ordering': ['create_on'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('weekday', models.CharField(blank=True, choices=[('Seg', 'Seg'), ('Ter', 'Ter'), ('Qua', 'Qua'), ('Qui', 'Qui'), ('Sex', 'Sex'), ('Sab', 'Sab')], help_text='*', max_length=10, verbose_name='Dia da semana')),
                ('curricular_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='school.CurricularComponent', verbose_name='CurricularComponent')),
                ('time_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='school.TimeTable', verbose_name='TimeTable')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'ordering': ['create_on'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('mode', models.CharField(blank=True, choices=[('Integrado', 'Integrado'), ('Subsequente', 'Subsequente'), ('Superior', 'Superior')], help_text='*', max_length=11, verbose_name='Forma')),
                ('period', models.IntegerField(verbose_name='Periodo Letivo')),
                ('class_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='school.ClassShift', verbose_name='ClassShift')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='school.Course', verbose_name='Course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='school.Semester', verbose_name='Semester')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['create_on'],
            },
        ),
        migrations.AddField(
            model_name='curricularcomponent',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curricular_components', to='school.Grade', verbose_name='Grade'),
        ),
        migrations.AddField(
            model_name='curricularcomponent',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curricular_components', to='accounts.Teacher', verbose_name='Teacher'),
        ),
    ]
