# Generated by Django 3.0.5 on 2022-06-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='dropzone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Dropzone'),
        ),
        migrations.AlterField(
            model_name='curricularcomponent',
            name='color',
            field=models.CharField(default='#FF0000', max_length=255, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='mode',
            field=models.CharField(blank=True, choices=[('Integrado', 'Integrado'), ('Subsequente', 'Subsequente'), ('Superior', 'Superior')], default='Integrado', help_text='*', max_length=11, verbose_name='Forma'),
        ),
    ]
