# Generated by Django 3.0.5 on 2022-06-05 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20220605_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='time_table',
        ),
    ]
