# Generated by Django 3.0.5 on 2022-06-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_remove_schedule_time_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='class_shift',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='dropzone',
        ),
        migrations.AddField(
            model_name='schedule',
            name='start',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Início da Aula'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='class_shift',
            field=models.CharField(blank=True, choices=[('0', 'Diurno/Manhã'), ('1', 'Diurno/Tarde'), ('2', 'Diurno/Integral'), ('3', 'Noturno')], default='0', help_text='*', max_length=15, verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='weekday',
            field=models.CharField(blank=True, choices=[('Seg', 'Seg'), ('Ter', 'Ter'), ('Qua', 'Qua'), ('Qui', 'Qui'), ('Sex', 'Sex'), ('Sab', 'Sab')], help_text='*', max_length=3, verbose_name='Dia da semana'),
        ),
        migrations.DeleteModel(
            name='ClassShift',
        ),
        migrations.DeleteModel(
            name='TimeTable',
        ),
    ]
