# Generated by Django 3.0.5 on 2022-05-07 20:59

from django.db import migrations, models
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axis',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school_days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Seg', 'Seg'), ('Ter', 'Ter'), ('Qua', 'Qua'), ('Qui', 'Qui'), ('Sex', 'Sex'), ('Sab', 'Sab')], max_length=23, verbose_name='Dias de Ensino'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=uuid.uuid4, max_length=150, unique=True, verbose_name='Email'),
        ),
    ]
